
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sintaxis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULTIPLICACION = 16;
  public static final int CLASS = 3;
  public static final int ELSE = 10;
  public static final int IGUAL = 13;
  public static final int INT = 7;
  public static final int WHILE = 11;
  public static final int FIN_LINEA = 26;
  public static final int DIVISION = 17;
  public static final int SUMA = 14;
  public static final int RETURN = 5;
  public static final int ERROR = 27;
  public static final int MAYOR_QUE = 23;
  public static final int IF = 9;
  public static final int RESERVADAS = 12;
  public static final int PUBLIC = 2;
  public static final int THIS = 4;
  public static final int MENOR_QUE = 22;
  public static final int FLOAT = 8;
  public static final int EOF = 0;
  public static final int PARENTESIS_C = 21;
  public static final int NUMERO = 19;
  public static final int error = 1;
  public static final int LLAVE_C = 25;
  public static final int PARENTESIS_A = 20;
  public static final int IDENTIFICADOR = 18;
  public static final int LLAVE_A = 24;
  public static final int VOID = 6;
  public static final int RESTA = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUBLIC",
  "CLASS",
  "THIS",
  "RETURN",
  "VOID",
  "INT",
  "FLOAT",
  "IF",
  "ELSE",
  "WHILE",
  "RESERVADAS",
  "IGUAL",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "IDENTIFICADOR",
  "NUMERO",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "MENOR_QUE",
  "MAYOR_QUE",
  "LLAVE_A",
  "LLAVE_C",
  "FIN_LINEA",
  "ERROR"
  };
}

